version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedule_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_app
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/schedule_db?sslmode=disable"
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["./schedules"]

volumes:
  postgres_data:
